source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Google/SignIn'
pod 'AFNetworking'
pod 'RealmSwift', '~> 0.97.1'
pod 'SSKeychain'
pod '1PasswordExtension'
pod 'FXBlurView'
pod 'Dropper'
pod 'AKPickerView-Swift'
pod 'SwiftyJSON'
