source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Google/SignIn'
pod 'AFNetworking'
pod 'RealmSwift'
pod 'SSKeychain'
pod '1PasswordExtension'
pod 'FXBlurView'
pod 'Dropper'
pod 'AKPickerView'
